<a href="https://colab.research.google.com/github/AyeshaM71/AyeshaM71/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [3]:
np.zeros(2)

array([0., 0.])

In [5]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
np.ones(3)

array([1., 1., 1.])

In [7]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [8]:
np.linspace(0,5,10) #gives a array with 10 even distributed numbers b/w 0 to 5

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])